package app.resources;

public final class Extension {
    public static final String FOLDER = "folder";
    public static final String TXT = "txt";
    public static final String PDF = "pdf";
    public static final String HTML = "html";
    public static final String HTM = "htm";
    public static final String FB2 = "fb2";
    public static final String EPUB = "epub";
    public static final String MOBI = "mobi";
    public static final String DOC = "doc";
    public static final String DOCX = "docx";
    public static final String XLS = "xls";
    public static final String XLSX = "xlsx";
    public static final String PPT = "ppt";
    public static final String PPTX = "pptx";
    public static final String DJVU = "djvu";
    public static final String ISO = "iso";
    public static final String ZIP = "zip";
    public static final String RAR = "rar";
    public static final String SEVENZ = "7z";
    public static final String GZIP = "gzip";
    public static final String JPG = "jpg";
    public static final String BMP = "bmp";
    public static final String JPEG = "jpeg";
    public static final String PNG = "png";
    public static final String GIF = "gif";
    public static final String TIF = "tif";
    public static final String MP3 = "mp3";
    public static final String WAV = "wav";
    public static final String MIDI = "midi";
    public static final String AAC = "aac";
    public static final String MP4 = "mp4";
    public static final String AVI = "avi";
    public static final String MKV = "mkv";
    public static final String WMV = "wmv";
    public static final String FLV = "flv";
    public static final String MPEG = "mpeg";
    public static final String EXE = "exe";
    public static final String BAT = "bat";
    public static final String CMD = "cmd";
    public static final String INI = "ini";
    public static final String UNKNOWN = "unknown";
    public static final String PARENT = "parent";
}
